### ISSUE TITLE
Missing on npmjs.com

### ISSUE THREAD

**Issue by Pamplemousse** [xwiki-labs/chainpad-listmap#3]
Other `chainpad*` components are available on https://www.npmjs.com/search?q=chainpad, but `chainpad-listmap` is missing from the list.

It would be nice to not depend on `bower`, which is a deprecated technology, to install this component.

**Comment by Pamplemousse** [comment]
Related to https://github.com/xwiki-labs/cryptpad/issues/295 .

**Comment by yflory** [comment]
`chainpad-listmap`is now available on npm. Thanks!
